Fail pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,6 +14,8 @@ jobs:
               uses: actions/checkout@v4
 
             - name: Run simple shell command
-              run: echo "Hello from cicd pipeline"
-              
+              run: |
+              echo "This will fail"
+              exit 1
+
 
